# Generated by Django 2.1.3 on 2018-12-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='desciption',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Dodaj zdjęcie'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='name',
            field=models.CharField(max_length=150, verbose_name='O czym marzysz?'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Darczyńca'),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='shop',
            field=models.CharField(max_length=250, verbose_name='Gdzie można to dostać?'),
        ),
    ]
