# Generated by Django 2.1.3 on 2018-12-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wish_list', '0003_auto_20181217_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=64)),
                ('desciption', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gifts',
            name='shop',
            field=models.CharField(max_length=250, null=True, verbose_name='Podaj link do sklepu internetowego'),
        ),
        migrations.AddField(
            model_name='donors',
            name='fundraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list.Fundraiser'),
        ),
        migrations.AddField(
            model_name='donors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
